# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/ for more details
#
version: 2.1
orbs:
  slack: circleci/slack@4.0.2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sudo apt-get update && sudo apt-get -y install python3-dev python3-pip libpython-dev
      - run: sudo pip3 install awscli
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: node docs/.vuepress/deploy.js $CIRCLE_TAG
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  version: 2
  publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /3\.[1-9]\..*/
