# Javascript Node CircleCI 2.1 configuration file
version: 2.1
orbs:
  slack: circleci/slack@4.4.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:12.22.10

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: sudo apt-get update && sudo apt-get install -y apt-transport-https
      - run: sudo apt-get update && sudo apt-get -y install python3-dev python3-pip libpython2-dev
      - run: sudo pip3 install awscli
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: node docs/.vuepress/deploy.js $CIRCLE_TAG
      - slack/notify:
          channel: C01D3B233DJ
          event: fail
          custom: |
            {
            	"blocks": [
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": ":red_circle: *Job Failed*: ${CIRCLE_JOB}"
            				}
            			]
            		},
            		{
            			"type": "context",
            			"elements": [
            				{
            					"type": "mrkdwn",
            					"text": "*Project*: $CIRCLE_PROJECT_REPONAME"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Branch*: $CIRCLE_BRANCH"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Author*: $CIRCLE_USERNAME"
            				}
            			]
            		},
            		{
            			"type": "actions",
            			"elements": [
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"text": "View Job"
            					},
            					"url": "${CIRCLE_BUILD_URL}"
            				}
            			]
            		}
            	]
            }
      - slack/notify:
          channel: C01D3B233DJ
          event: pass
          custom: |
            {
            	"blocks": [
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": ":white_check_mark: *Job Success*: ${CIRCLE_JOB}"
            				}
            			]
            		},
            		{
            			"type": "context",
            			"elements": [
            				{
            					"type": "mrkdwn",
            					"text": "*Project*: $CIRCLE_PROJECT_REPONAME"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Branch*: $CIRCLE_BRANCH"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Author*: $CIRCLE_USERNAME"
            				}
            			]
            		},
            		{
            			"type": "actions",
            			"elements": [
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"text": "View Job"
            					},
            					"url": "${CIRCLE_BUILD_URL}"
            				}
            			]
            		}
            	]
            }
  update_index:
    machine:
      image: cimg/base:2020.01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: algolia
          command: |
            /bin/bash scripts/_docsearch.sh
workflows:
  publish:
    jobs:
      - build:
          context:
            - slack-secrets
          filters:
            branches:
              only:
                - /4\.[0-9]\..*/
            tags:
              only: /^v.*/
      - update_index:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
